### ISSUE TITLE
GUI Dev

### ISSUE THREAD

**Issue by annimesh2809** [KRSSG/robocup#1]
This issue will serve for any queries and updates regarding the GUI development.

**Comment by annimesh2809** [comment]
@KgpKubs/gui Install `PyQt5` and `QtDesigner` (or `QtCreator`) (stable versions).

@KgpKubs/all For the **current** simple case, I was thinking of a simple API like:

### Communication protocol (rosmsgs):

#### Path Planner ---> GUI

rgb.msg
```
uint8 r
uint8 g
uint8 b
```

point.msg
 ```
int32 x
int32 y
 ```

path.msg
```
point[] vertices
rgb color
```
The gui will subscribe for `path.msg` type data and will redraw the path everytime it recieves a ros message.
#### GUI ---> Path Planner

Some parameters for controlling step-size etc. (This msg should be defined by @KgpKubs/path)

### Function prototype (would be implemented in Python)
```cpp
err_f ssl::gui::debug_path(const path& p);
```

Does this look fine? Any changes?

**Comment by MayankB11** [comment]
LGTM

**Comment by kvmanohar22** [comment]
Let's change `int32 x`, `int32 y` in `point.msg` to `float x`, `float y`. Have a look at [this](https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/shared/proto/messages_robocup_ssl_detection.proto#L14-L15)

**Comment by annimesh2809** [comment]
@kvmanohar22 That makes sense for calculation of velocities and other floating point calculations. However for drawing lines, I think it would be more suitable to use integer values (until of course we start using anti-aliasing with `xiaolin-wu`?). Take a look a [this `drawLine` function definiton](http://doc.qt.io/qt-4.8/qpainter.html#drawLine-5) from QPainter.

**Comment by annimesh2809** [comment]
@KgpKubs/gui You guys can start working on this. Any queries should be posted on this issue.

**Comment by ashishkg0022** [comment]
@sipah00 see I have written the code #2 . Please start working on it.

**Comment by sipah00** [comment]
@ashishkg0022 I have gone through code, and i am working on this.
